In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math 
from random import randrange

In [2]:
list = [[1,2,3],[5,6,7]]

In [3]:
z = np.array([list])

In [4]:
print (z)

[[[1 2 3]
  [5 6 7]]]


In [5]:
z

array([[[1, 2, 3],
        [5, 6, 7]]])

In [6]:
z.shape

(1, 2, 3)

In [7]:
z

array([[[1, 2, 3],
        [5, 6, 7]]])

In [8]:
z

array([[[1, 2, 3],
        [5, 6, 7]]])

In [9]:
z

array([[[1, 2, 3],
        [5, 6, 7]]])

In [14]:
z

array([[[1, 2, 3],
        [5, 6, 7]]])